### ISSUE TITLE
What patch is this?

### ISSUE THREAD

**Issue by kreatoo** [bakkeby/dusk#1]
What patch do you use to do https://raw.githubusercontent.com/wiki/bakkeby/dwm-vanitygaps/dusk_scr01.gif ? I'd like to know because i am looking for such behaviour on my dwm. Thanks.

**Comment by bakkeby** [comment]
I don't have standalone dwm patches for everything in this build, but in this particular case you are looking at the [placemouse](https://github.com/bakkeby/patches/wiki/placemouse) patch.

**Comment by kreatoo** [comment]
Thank you!
