### ISSUE TITLE
restart fails to restart when nm-applet was autostarted

### ISSUE THREAD

**Issue by andbenn** [bakkeby/dusk#14]
restart doesn't restart
quit doesn't quit cleanly

(sorry, don't have the exact errors, but can get them if needed).

I merged in some of the recent code changes.  Built dusk.
Used my keybinding for restart
I believe autostarted processes stopped as expected
Boom.  I'm back at a tty looking at an error

startx to get dusk going

keybinding for quit
// does not seem to quit cleaning

startx to get dusk going
keybinding for restart
// same behavior as before

Let me know if versions of any packages/libraries are needed.  Arch system was up to date as of Sunday with kernel (lts) and related.

**Comment by bakkeby** [comment]
> I merged in some of the recent code changes.

👀 What do you mean? You don't just do a `git pull --rebase`?

I wasn't able to replicate using the default config, would it be possible for you to share yours?

**Comment by andbenn** [comment]
Erm, let's remove quit from this issue.  I may have gotten confused.  Let's stick with restart.  Summary updated.

Narrowing down what is in my dusk autostart, and leaving only nm-applet as being present, I can't get dusk to restart with that keybinding.

Remove nm-applet and add back all of my other programs to autostart, I can restart dusk cleanly.

Just nm-applet by itself in autostart, dusk can't restart.

network-manager-applet is 1.28.0-1 build date of 20 June 2022
networkmanager is 1.40.0-1 build date of 3 Sept 2022

My hope is you are using an Arch or Arch based distro and might be able to reproduce this.  Or we can go to discord and find another willing victim.  If you can think of something creative for me to do, I'm all ears/eyes/fingers.

Granted, I am using Artix on the laptop where I see this, and Artix does their own builds of the Arch code for the packages in their repo, such as the candidate networkmanager package that blocks dusk from restarting.  But why?

On code management, I have a clone of your code that I pull and update.  I then merge new changes there into my separate code, which is 1:1 except for the config.h file.  It's my feeble attempt to become familiar and watch your changes as I apply them from yours to mine.

**Comment by andbenn** [comment]
Update: starting nm-applet in a shell and backgrounding it, I am able to restart dusk.

It may be that nm-applet is not a good autostart candidate.  But this used to work.

**Comment by bakkeby** [comment]
As discussed in chat this had to do cleaning up and unmapping systray windows after the process had been killed, which resulted in a segmentation fault when calling `XSync`. Writeup in the commit comment.

**Comment by andbenn** [comment]
Looks great!  I'm OK to close this unless you had more you wanted to do.  Consider it accepted - thank you!
