### ISSUE TITLE
Arabic and Right-to-Left Languages is NOT rendered Correctly.

### ISSUE THREAD

**Issue by 0xUnixy** [bakkeby/dusk#19]
Hi @bakkeby thanks for this amazing fork of `DWM` it's working **great**;
but there is a simple problem with an easy fix and it's that Arabic and right-to-left languages are not rendered probably on the bar, it looks like this.
![image](https://github.com/bakkeby/dusk/assets/137896711/a6ad9767-3268-4d7d-beaa-dbff8c4809a6)

* There is a patch in `DWM` website called [bidi](https://dwm.suckless.org/patches/bidi/) BUT i don't know how to put it in `dusk`.
thanks again.

**Comment by bakkeby** [comment]
I was thinking of adding this as a patch, but maybe it is OK to add this as an optional dependency.

Taking a random YouTube video as an example test case:
   - https://www.youtube.com/watch?v=TugIwOsbDvI

Without the patch:
![image](https://github.com/bakkeby/dusk/assets/1438008/e6e31a22-2ca9-48af-b1ba-70844b838764)

With the patch:
![image](https://github.com/bakkeby/dusk/assets/1438008/698caea0-43b8-4a1d-8448-0d6a323ba1c3)

The video title on the site, however, looks like this:
![image](https://github.com/bakkeby/dusk/assets/1438008/0f9b07b8-1b6f-4a73-981a-30ac9609bbc9)

In our case, using the fribidi library, we reverse the whole text, whereas it looks like on YouTube the RTL text sections are reversed while the general composition of the text is kept. Not sure which method is more correct, I'd assume that the fribidi way makes more sense.

**Comment by bakkeby** [comment]
To test these changes all you need, besides having the fribidi library installed, is to uncomment the following lines in config.mk:

https://github.com/bakkeby/dusk/blob/6c4d3da2fb6b224ce70b557664cb4d00e33aa2e0/config.mk#L22-L25

**Comment by 0xUnixy** [comment]
Thanks alot @bakkeby for the fast response and active development of this **great project**.
i have tested it and it worked as intended, here is my test case:
![image](https://github.com/bakkeby/dusk/assets/137896711/088faa47-066e-4e54-b008-7b6462949f52)

Thanks, **C ninja** ;)
