### ISSUE TITLE
how to deactivate bottombar?

### ISSUE THREAD

**Issue by deltahoch3** [bakkeby/dusk#20]
howdy,
first of all, i really like DUSK :)

one thing i can't get my head around:

how do i deactivate the bottombar? in my flexipatch dwm-setup when i hide a client/tag i stays in the topbar, but only the color changes.... 
is this also possible?

cheers and thnaks in advanced

**Comment by bakkeby** [comment]
You can configure 0 or more bars per monitor, and each bar can have 0 or more modules which provide content.
The [Bar](https://github.com/bakkeby/dusk/wiki/Bar) wiki page is a good place to start.

I also have a [guide](https://github.com/bakkeby/dusk/wiki/How_to_customise_your_bar) if you want to play around with setting up the bar(s) from scratch.

----

> how do i deactivate the bottombar?

If a bar has nothing to display then the bar itself does not display.

The default configuration defines a top and a bottom bar for up to three monitors.

https://github.com/bakkeby/dusk/blob/354a9ca122f705ba446a0d193337bd710f08542b/config.def.h#L314-L322

If you look at the bar rules there are the following modules that are placed on the bar with index 1 (i.e. the bottom bar).

https://github.com/bakkeby/dusk/blob/354a9ca122f705ba446a0d193337bd710f08542b/config.def.h#L373-L376

If you want to deactivate the bottom bar then all you need to do is to remove those three modules. You can also remove the rows from the `bars` array if you want, but this is not necessary.

----

> in my flexipatch dwm-setup when i hide a client/tag i stays in the topbar, but only the color changes....
> is this also possible?

In the bar rules there is a module that draws the window titles:

https://github.com/bakkeby/dusk/blob/354a9ca122f705ba446a0d193337bd710f08542b/config.def.h#L371

There is some general information about this on the [FlexWinTitle Module](https://github.com/bakkeby/dusk/wiki/FlexWinTitle-Module) wiki page.

The _size_ of the window titles drawn are _relative_ to the number of clients and the category of clients. This means that the window titles for master clients can be larger than the window titles of stack clients, as an example.

The way this works is that each category is given a _weight_ that is relative to the weight of other categories.

The default configuration for this is as follows:

https://github.com/bakkeby/dusk/blob/354a9ca122f705ba446a0d193337bd710f08542b/config.def.h#L112-L115

The way to read this is that master client window titles are almost four times larger than the window titles of stack clients. The weight of hidden and floating window titles are set to 0, which in practice means do not show hidden and floating window titles.

The reason for this is that floating and hidden clients are shown on demand on the bottom bar as per the bar rules mentioned earlier (and we do not want the window titles to appear in two places).

As such all you need to do is to set the `flexwintitle_hiddenweight` and `flexwintitle_floatweight` to 1 to have them display in the top bar similarly to how you had it in dwm.

If you set the weight to be the same across master, stack, hidden and floating then all window titles will have the same size and it will look similar to what awesomebar look like.
