### ISSUE TITLE
ViewOnWS does not work

### ISSUE THREAD

**Issue by Nazushvel** [bakkeby/dusk#21]
Looks like currently behavior with both ViewOnWS enabled/disabled is the same. leaving it commented out still switches workspace when you move a window and does the same when it is uncommented. 

Also to confirm I tried it unmodified and got the same result.

Also, thanks for this awesome application. Been looking for something to fit my workflow for years and looks like this is just what I have been looking for.

**Comment by Nazushvel** [comment]
Well I feel dumb, I see now that shift does that and ctrl does not. Guess I should have read the instructions a bit better. Closing as non issue

**Comment by bakkeby** [comment]
Yes. To give a bit more context for other people reading this the [ViewOnWs](https://github.com/bakkeby/dusk/wiki/ViewOnWs) functionality intends to mirror the [viewontag](https://dwm.suckless.org/patches/viewontag/) patch for dwm which makes the view follow the tag a window is being moved to.

But that feature makes it always the case when moving windows around, and sometimes you may want to:
- move a specific window to another tag / workspace and continue working on it there or
- just move one or more windows away to another tag

As such the behaviour was split into two separate functions:
- [movetowsbyname](https://github.com/bakkeby/dusk/wiki/movetowsbyname)
- [sendtowsbyname](https://github.com/bakkeby/dusk/wiki/sendtowsbyname)

https://github.com/bakkeby/dusk/blob/acedf00c7289a2843b0e78b2c101f41f7401b5c0/config.def.h#L453-L460

Now, what is the purpose of the `ViewOnWs` functionality in dusk then considering that this is controlled by different functions?

The functionality toggle controls the _default_ behaviour for other scenarios where clients are being moved around. For example [movewsdir](https://github.com/bakkeby/dusk/wiki/movewsdir), [movews](https://github.com/bakkeby/dusk/wiki/movews), [movealltowsbyname](https://github.com/bakkeby/dusk/wiki/movealltowsbyname), [clienttomon](https://github.com/bakkeby/dusk/wiki/clienttomon), [clientstomon](https://github.com/bakkeby/dusk/wiki/clientstomon), or when `_NET_ACTIVE_WINDOW` client messages are received and the [FocusOnNetActive](https://github.com/bakkeby/dusk/wiki/FocusOnNetActive) functionality is enabled.
