### ISSUE TITLE
Is Dusk maintained seaprately from dwm?

### ISSUE THREAD

**Issue by SisyphusIsntHappy** [bakkeby/dusk#23]
Forgive the ignorance. What I mean is that whether further modifications in dwm will be integrated into dusk?

**Comment by bakkeby** [comment]
dusk is maintained separately to dwm.

If there are changes made to dwm that is an improvement and would still apply to dusk then chances are that I'd incorporate them. For example the font handling in `drw.c` is very much the same between the two.
