### ISSUE TITLE
question: is it possible so multiple hidden clients? "showhideclients"

### ISSUE THREAD

**Issue by deltahoch3** [bakkeby/dusk#28]
howdy again,

one more question:
**is it possible to unhide multiple clients?**
i quite like the hide behavior, but its only working with a mouse if i hide multiple clients (right-click on the title in the bar).

would it be possible to hide clients one-by-one with "super + z" and bring one-by-one  back with "super + shift + z" ?

i think i asked this before but in a dwm context, but i believe it was not possible...

thanks in advanced
hardy

**Comment by bakkeby** [comment]
Funny, while trying to think of a good name for such a function I though "unhidepop" might be a good fit.

Then I found that I already have such a function:
https://github.com/bakkeby/dusk/wiki/unhidepop

There is no default keybinding for this, but you can add one.

```c
{ KeyPress,   Super|Shift,                  XK_z,            unhidepop,              {0} },
```

I believe that should behave the way you describe.

In this context you could also do a Super + a (select all) and do Super + z to hide all visible clients on the current workspace.

**Comment by deltahoch3** [comment]
yeahhh :smile: 

works exactly as i imagined, thanks for your help!!
