### ISSUE TITLE
in wiki, "broken link"...

### ISSUE THREAD

**Issue by GitDalex** [bakkeby/dusk#5]
hello,
in the page configuration, when arriving on Icon section this :  
"Refer to the flexwintitle page for more details. "    sends you back to the "cover" of the wiki...
And I tried to locate if there is such page but I was unsuccessful.

sorry english isn't my native language.(It was pretty fun to adapt the keyboard to have dusk working...)
have a good day(and a good year, it's the season ^^)

**Comment by bakkeby** [comment]
Thanks for letting me know, I have corrected that link now. Much appreciated.
